### ISSUE TITLE
Add/map after the initial create

### ISSUE THREAD

**Issue by qmmr** [cesarenaldi/iniettore#8]
Given the API changes in the v2.0, it seems that we no longer can add additional mappings after the `rootContext` has been created. In v0.4 it was possible to do `binding` after the `context` was created:

``` js
var context = iniettore.create(function(context) {
    context.bind('foo', Foo)
        .as(SINGLETON, PROVIDER)
        .inject(['deps'])
        .done();
});

// later on...

context.bind('bar', Bar).as(SINGLETON, CONSTRUCTOR).done();
```

What is the proposed workaround?

**Comment by cesarenaldi** [comment]
Yes, this is a design decision. The contribution phase of a context has to be synchronous and terminates with the factory function callback.

If you need to contribute more entries you can use a new child context.

**Comment by cesarenaldi** [comment]
Can you provide more details on the use case you need to support?

**Comment by cesarenaldi** [comment]
Closing issue.
