### ISSUE TITLE
Multiple exports from a child context

### ISSUE THREAD

**Issue by krasimir** [cesarenaldi/iniettore#9]
What you think if the `exports` method supports multiple arguments. So the following is possible:

```js
import iniettore from 'iniettore'
import { VALUE, FUNCTION, BLUEPRINT } from 'iniettore'

function baz(bar) {
	console.log(bar)
}
function boo(bar) {
	console.log(bar * 2)
}

function configureChildContext(map) {
	map('baz').to(baz).as(FUNCTION).injecting('bar')
	map('boo').to(boo).as(FUNCTION).injecting('bar')
}

var rootContext = iniettore.create(function (map) {
	map('bar').to(42).as(VALUE)
	map(['A', 'B']).to(configureChildContext).as(BLUEPRINT).exports('baz', 'boo')
})

var baz = rootContext.get('A')
var boo = rootContext.get('B')

console.log(baz()) // 42
console.log(boo()) // 84
```

**Comment by cesarenaldi** [comment]
I am not too sure about the current Blueprint implementation. I find that the parent context needs to know too much about the Blueprint context factory internals just by knowing one of the binding name.

I feel that adding more increase this knowledge. Ideally I would love for the child context factory to be able to "elect" one of the binding as "default export".

The similarities in names with the ES module system might suggest that a "named export" could also be a desirable feature. I would like to discuss more on implications and real life use cases. I don't want give the impression _iniettore_ is an "alternative/less-powerful module system". It is NOT! It's more of a complementary tool to the native module system.

If the use case for using a child context (and Blueprints are just child context factories), what is the point of exporting more than one thing? If you have 2 composition layers why cram them into the same context and not compose them separately?

Can you think about some real life examples?

**Comment by krasimir** [comment]
I do remember that I was trying to solve a dependency problem. What was the exact case however is out of my memory. But I also remember that we had a chat about this and we solved the problem without the need of such change. Also I agree with this

> If the use case for using a child context (and Blueprints are just child context factories), what is the point of exporting more than one thing? If you have 2 composition layers why cram them into the same context and not compose them separately?

Exactly.
